resolver: nightly-2016-05-21
compiler: ghc-8.0.1
packages:
- '.'
extra-deps:
- array-0.5.1.1
- containers-0.5.7.1
- deepseq-1.4.2.0
- directory-1.2.6.3
- filepath-1.4.1.0
- process-1.4.2.0
- transformers-0.5.2.0
- transformers-compat-0.5.1.4
- unix-2.7.2.0
flags: {}
extra-package-dbs: []